HsdiTechLeaveSys/config/routes.rb
Rails.application.routes.draw do
  resources :leave_records
  resources :staffs
  get 'login_sys/login_pag'
  post 'login_sys/check_login'
  get 'leave_records/excel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'login_sys#login_pag'
end

HsdiTechLeaveSys/app/models/leave_record.rb
class LeaveRecord < ApplicationRecord
end

HsdiTechLeaveSys/app/controllers/leave_records_controller.rb
class LeaveRecordsController < ApplicationController
  before_action :set_leave_record, only: [:show, :edit, :update, :destroy]
  # GET /leave_records
  # GET /leave_records.json
  def index
    @leave_records = LeaveRecord.all
    for record in @leave_records
      record.leave_type = convertLeaveType(record.leave_type)
    end
  end

  # GET /leave_records/1
  # GET /leave_records/1.json
  def show
    @leave_record.leave_type = convertLeaveType(@leave_record.leave_type)
  end

  # GET /leave_records/new
  def new
    @leave_record = LeaveRecord.new
    @status='new'
  end

  # GET /leave_records/1/edit
  def edit
    @status='edit'
  end

  def excel
    #render :text =>@leave_record.attributes
    send_data get_xml_str, :filename => 'Leave Application.xml', :type => "text/comma-separated-values", :disposition => "attachment"
  end

  # POST /leave_records
  # POST /leave_records.json
  def create
    @leave_record = LeaveRecord.new(leave_record_params)
    @leave_record.staff_id='1'
    @leave_record.state='0'
    respond_to do |format|
      if @leave_record.save
        format.html { redirect_to @leave_record, notice: 'Leave record was successfully created.' }
        format.json { render :show, status: :created, location: @leave_record }
      else
        format.html { render :new }
        format.json { render json: @leave_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leave_records/1
  # PATCH/PUT /leave_records/1.json
  def update
    respond_to do |format|
      if @leave_record.update(leave_record_params)
        format.html { redirect_to @leave_record, notice: 'Leave record was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave_record }
      else
        format.html { render :edit }
        format.json { render json: @leave_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_records/1
  # DELETE /leave_records/1.json
  def destroy
    @leave_record.destroy
    respond_to do |format|
      format.html { redirect_to leave_records_url, notice: 'Leave record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_leave_record
    if params[:id]=='excel'
      @leave_record = LeaveRecord.find(params[:recoed])
      excel
    else
      @leave_record = LeaveRecord.find(params[:id])
    end

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def leave_record_params
    params.require(:leave_record).permit(:staff_id, :from_date, :to_date, :apply_date, :reason, :leave_type, :state)
  end

  def convertLeaveType(type_num)
    result='Others'
    case type_num
    when '1'
      result='Annual Leave'
    when '2'
      result='Public Holiday'
    when '3'
      result='Compensatory Days'
    when '4'
      result='Sick Leave'
    when '5'
      result='Marriage Leave'
    when '6'
      result='Maternity Leave'
    when '7'
      result='Unpaid Leave'
    when '8'
      result='Study Leave'
    when '9'
      result='Others'
    else
    result='Others'
    end
  end

  def get_xml_str
    return %(
<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Author>Chee</Author>
  <LastAuthor>Yu Yong</LastAuthor>
  <LastPrinted>2017-01-03T10:06:39Z</LastPrinted>
  <Created>2003-01-08T16:16:33Z</Created>
  <LastSaved>2017-01-22T02:04:22Z</LastSaved>
  <Company>Home</Company>
  <Version>14.00</Version>
 </DocumentProperties>
 <CustomDocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <KSOProductBuildVer dt:dt="string">2052-10.1.0.6065</KSOProductBuildVer>
 </CustomDocumentProperties>
 <OfficeDocumentSettings xmlns="urn:schemas-microsoft-com:office:office">
  <AllowPNG/>
 </OfficeDocumentSettings>
 <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
  <WindowHeight>7875</WindowHeight>
  <WindowWidth>20730</WindowWidth>
  <WindowTopX>0</WindowTopX>
  <WindowTopY>0</WindowTopY>
  <ProtectStructure>False</ProtectStructure>
  <ProtectWindows>False</ProtectWindows>
 </ExcelWorkbook>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Arial" x:Family="Swiss"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="s16">
   <Interior/>
  </Style>
  <Style ss:ID="s17">
   <Borders>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s18">
   <Borders>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s19">
   <Borders>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s20">
   <Borders/>
   <Interior/>
  </Style>
  <Style ss:ID="s21">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s22">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
   <NumberFormat ss:Format="[ENG][$-409]d\-mmm\-yy;@"/>
  </Style>
  <Style ss:ID="s23">
   <Alignment ss:Horizontal="Right" ss:Vertical="Bottom"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
   <NumberFormat ss:Format="[ENG][$-409]d\-mmm\-yy;@"/>
  </Style>
  <Style ss:ID="s24">
   <Borders>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Arial" x:Family="Swiss" ss:Bold="1"/>
   <Interior/>
  </Style>
  <Style ss:ID="s25">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s26">
   <Borders>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Arial" x:Family="Swiss" ss:Bold="1" ss:Italic="1"/>
   <Interior/>
  </Style>
  <Style ss:ID="s27">
   <Borders/>
   <Font ss:FontName="Monotype Corsiva" x:Family="Script" ss:Size="12"/>
   <Interior/>
  </Style>
  <Style ss:ID="s28">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s29">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
   <NumberFormat ss:Format="[ENG]d\-mmm"/>
  </Style>
  <Style ss:ID="s30">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
   <NumberFormat ss:Format="[ENG][$-409]d\-mmm\-yy;@"/>
  </Style>
  <Style ss:ID="s31">
   <Alignment ss:Horizontal="Left" ss:Vertical="Bottom"/>
   <Borders>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s32">
   <Borders>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s33">
   <Borders>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s34">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s35">
   <Borders>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Arial" x:Family="Swiss" ss:Underline="Single"/>
   <Interior/>
  </Style>
  <Style ss:ID="s36">
   <Borders/>
   <Font ss:FontName="Arial" x:Family="Swiss" ss:Underline="Single"/>
   <Interior/>
  </Style>
  <Style ss:ID="s37">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Arial" x:Family="Swiss" ss:Underline="Single"/>
   <Interior/>
  </Style>
  <Style ss:ID="s38">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Arial" x:Family="Swiss"/>
   <Interior/>
  </Style>
  <Style ss:ID="s39">
   <Borders/>
   <Font ss:FontName="Arial" x:Family="Swiss"/>
   <Interior/>
  </Style>
  <Style ss:ID="s40">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
  </Style>
  <Style ss:ID="s41">
   <Alignment ss:Horizontal="Left" ss:Vertical="Bottom"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Interior/>
   <NumberFormat ss:Format="Medium Date"/>
  </Style>
  <Style ss:ID="s42">
   <Borders>

HsdiTechLeaveSys/app/helpers/leave_records_helper.rb
module LeaveRecordsHelper
end

HsdiTechLeaveSys/app/views/leave_records/_form.html.erb
<%= form_for(leave_record) do |f| %>
<% if leave_record.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(leave_record.errors.count, "error") %> prohibited this leave_record from being saved:</h2>

	<ul>
		<% leave_record.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<%if !(@status=='new' || @status=='edit')%>
<div class="field">
	<%= f.label :staff_id %>
	<%= f.text_field :staff_id %>
</div>
<%end%>

<div class="field">
	<%= f.label :from_date %>
	<%= f.datetime_select :from_date %>
</div>

<div class="field">
	<%= f.label :to_date %>
	<%= f.datetime_select :to_date %>
</div>

<div class="field">
	<%= f.label :apply_date %>
	<%= f.datetime_select :apply_date %>
</div>

<div class="field">
	<%= f.label :reason %>
	<%= f.text_area :reason,"cols" => 50, "rows" => 10 %>
</div>

<div class="field">
	<%= f.label :leave_type %>
	<%= f.select :leave_type ,{"Annual Leave"=>'1',"Public Holiday"=>'2',"Compensatory Days"=>'3',"Sick Leave"=>'4',"Marriage Leave"=>'5',"Maternity Leave"=>'6',"Unpaid Leave"=>'7',"Study Leave"=>'8',"Others"=>'9'}%>
</div>
<%if !(@status=='new' || @status=='edit')%>
<div class="field">
	<%= f.label :state %>
	<%= f.text_field :state %>
</div>
<% end %>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

HsdiTechLeaveSys/app/views/leave_records/edit.html.erb
<h1>Editing Leave Record</h1>

<%= render 'form', leave_record: @leave_record %>

<%= link_to 'Show', @leave_record %> |
<%= link_to 'Back', leave_records_path %>

HsdiTechLeaveSys/app/views/leave_records/index.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1>Leave Records</h1>

<table border="1">
	<thead>
		<tr>
			<th>Staff</th>
			<th>From date</th>
			<th>To date</th>
			<th>Apply date</th>
			<th>Reason</th>
			<th>Leave type</th>
			<th>State</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @leave_records.each do |leave_record| %>
		<tr>
			<td><%= leave_record.staff_id %></td>
			<td><%= leave_record.from_date %></td>
			<td><%= leave_record.to_date %></td>
			<td><%= leave_record.apply_date %></td>
			<td><%= leave_record.reason %></td>
			<td><%= leave_record.leave_type %></td>
			<td><%= leave_record.state %></td>
			<td><%= link_to 'Show', leave_record %></td>
			<td><%= link_to 'Edit', edit_leave_record_path(leave_record) %></td>
			<td><%= link_to 'Destroy', leave_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Leave Record', new_leave_record_path %>

HsdiTechLeaveSys/app/views/leave_records/new.html.erb
<h1>New Leave Record</h1>

<%= render 'form', leave_record: @leave_record %>

<%= link_to 'Back', leave_records_path %>

HsdiTechLeaveSys/app/views/leave_records/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<strong>Staff:</strong>
	<%= @leave_record.staff_id %>
</p>

<p>
	<strong>From date:</strong>
	<%= @leave_record.from_date %>
</p>

<p>
	<strong>To date:</strong>
	<%= @leave_record.to_date %>
</p>

<p>
	<strong>Apply date:</strong>
	<%= @leave_record.apply_date %>
</p>

<p>
	<strong>Reason:</strong>
	<%= @leave_record.reason %>
</p>

<p>
	<strong>Leave type:</strong>
	<%= @leave_record.leave_type %>
</p>

<p>
	<strong>State:</strong>
	<%= @leave_record.state %>
</p>

<%= link_to 'Edit', edit_leave_record_path(@leave_record) %> |
<%= link_to 'Back', leave_records_path %> |
<%= link_to 'Excel', {:controller => "leave_records",:action => 'excel',:recoed=> @leave_record},{}%>