HsdiTechLeaveSys/config/routes.rb
Rails.application.routes.draw do
  resources :leave_records
  resources :staffs
  get 'login_sys/login_pag'
  post 'login_sys/check_login'
  get 'leave_records/excel'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'login_sys#login_pag'
end

HsdiTechLeaveSys/app/models/staff.rb
class Staff < ApplicationRecord
end

HsdiTechLeaveSys/app/controllers/staffs_controller.rb
#require 'digest/md5'
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)
    @staff.password_md5=Digest::MD5::hexdigest(@staff.password_md5)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_staff
    @staff = Staff.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def staff_params
    params.require(:staff).permit(:name, :username, :password_md5, :position, :email)
  end
end

HsdiTechLeaveSys/app/helpers/staffs_helper.rb
module StaffsHelper
end

HsdiTechLeaveSys/app/views/staffs/_form.html.erb
<%= form_for(staff) do |f| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password_md5 %>
    <%= f.text_field :password_md5 %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HsdiTechLeaveSys/app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

HsdiTechLeaveSys/app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password md5</th>
      <th>Position</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.username %></td>
        <td><%= staff.password_md5 %></td>
        <td><%= staff.position %></td>
        <td><%= staff.email %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

HsdiTechLeaveSys/app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

HsdiTechLeaveSys/app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @staff.username %>
</p>

<p>
  <strong>Password md5:</strong>
  <%= @staff.password_md5 %>
</p>

<p>
  <strong>Position:</strong>
  <%= @staff.position %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>